services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: gpu-monitor-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: gpu-monitor-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./src/frontend/src:/app/src
      - ./src/frontend/public:/app/public
      - ./src/frontend/tailwind.config.js:/app/tailwind.config.js