# Use Node.js v20
FROM node:20

WORKDIR /app

# Copy package.json and package-lock.json
COPY src/frontend/package.json src/frontend/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the entire frontend code
COPY src/frontend ./

# Generate the TailwindCSS build
RUN npx tailwindcss -i ./src/index.css -o ./src/output.css

# Start the frontend
CMD ["npm", "start"]
